name: PHPStan

on:
  push:
    branches: [master]
    paths:
      - '**.php'
      - 'ruleset.xml'
      - 'composer.json'
  pull_request:
    branches: [master]
    paths:
      - '**.php'
      - 'ruleset.xml'
      - 'composer.json'

jobs:
  phpcs-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: PHPStan
        run: composer phpstan